### ISSUE TITLE
2019 Worlds link at the end of the page redirects to 2020 Worlds

### ISSUE THREAD

**Issue by cehidalgo** [rocket3989/worlds-2019#2]
Hi, guys!
First of all, thanks for the app. As an fanatic e-sports fan and been keep an eye in this years' worlds, I admire a lot your work.

That being said, I think I've found a little bug when I went to see the other events linked in the bottom of page. Very straight forward on this: the a tag link saying **2019 Worlds** at the end of the page basically redirects the user to the top of the page due to the URL being the same of the page already loaded, instead of the 2019 Worlds _de facto_ URL.

It's a very simple matter, I can fix it for you and make a PR if you want. Just message me!

Once again, thanks for the app.

See you soon!
**Carlos** o/

**Comment by rocket3989** [comment]
Thanks! looks like I got a little too frantic in my hunt for 2019's to change to 2020's
